[env:esp32-c6-devkitc-1]
platform  = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
board     = esp32-c6-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

upload_port   = COM5     
monitor_port  = COM5 

monitor_filters = 
    esp32_exception_decoder
    default

; ---- IMPORTANTE: Desactivar USB-CDC ----
build_flags =
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=0

lib_deps =
    h2zero/NimBLE-Arduino @ ^2.1.0
    knolleary/PubSubClient @ ^2.8

build_src_filter =
    +<*>
    +<drivers/*>